git:
    depth: 1
language: python
install:
    - pip install 'setuptools>=36.2.1'
    - pip install .
    - pip install codecov
script:
    - cd tests
    - coverage run __main__.py
python:
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: 3.7  # travis-ci/issues/9815
      dist: xenial
      sudo: true
    - python: nightly  # travis-ci/issues/9815
      dist: xenial
      sudo: true
after_success:
    - codecov
